SchoolManagement/SchoolManagement/Areas/Student/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.DAL;

namespace SchoolManagement.Areas.Student.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student/Student
        private StudentDAL dal = new StudentDAL();

        #region Study
        public ActionResult Index()
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 3)
                {
                    return View();
                }
                else { return View("Error"); }
            }
            catch { return View("Error"); }
        }

        public ActionResult Schedule()
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 3)
                {
                    string mssv = Session["ID"].ToString();
                    return View(dal.Schedule(mssv).OrderBy(s => s.Class_Subjects.Time));
                }
                else { return View("Error"); }
            }
            catch { return View("Error"); }
        }

        public ActionResult Grades()
        {

            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 3)
                {
                    string mssv = Session["ID"].ToString();
                    return View(dal.GredeByID(mssv));
                }
                else { return View("Error"); }
            }
            catch { return View("Error"); }
        }
        #endregion

        #region Register Subjects
        public ActionResult RegSubject()
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 3)
                {
                    string mssv = Session["ID"].ToString();
                    ViewBag.Check = CheckDAL.CheckActive(Session["ID"].ToString(), false);
                    return View(dal.ListRegSubject(mssv));
                }
                else { return View("Error"); }
            }
            catch { return View("Error"); }
        }

        public ActionResult CreateRegSubject(string idSubject)
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 3 && idSubject != null)
                {
                    string mssv = Session["ID"].ToString();
                    dal.RegisterSubject(mssv, idSubject);
                    //ViewBag.MessageReg = "Register successfull!";
                    //CheckDAL.MessageAlert("Register successfull!");
                    return RedirectToAction("RegSubject");
                }
                else { /*CheckDAL.MessageAlert("Code not true. Please try it"); */return View("Error"); }
            }
            catch
            {
                ViewBag.MessageReg = "Wrong IdSubject :(";
                return RedirectToAction("RegSubject");
            }
        }

        public ActionResult DeleteSubject(int? id)
        {
            if (id.HasValue)
            {
                dal.DeleteSubject(id.Value);
            }
            return RedirectToAction("RegSubject");
        }
        #endregion

        #region Register Classes
        public ActionResult RegClass()
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 3)
                {
                    string mssv = Session["ID"].ToString();
                    ViewBag.Check = CheckDAL.CheckActive(Session["ID"].ToString(), true);
                    return View(dal.Schedule(mssv));
                }
                else { return View("Error"); }
            }
            catch { return View("Error"); }
        }

        public ActionResult CreateRegClass(string idClass)
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 3 && idClass != null)
                {
                    string mssv = Session["ID"].ToString();
                    dal.RegisterClass(mssv, idClass);

                    return RedirectToAction("RegClass");
                }
                else { return View("Error"); }
            }
            catch
            { return RedirectToAction("RegClass"); }
        }

        public ActionResult DeleteClass(int? id)
        {
            if (id.HasValue)
            {
                dal.DeleteClass(id.Value);
            }
            return RedirectToAction("RegClass");
        }
        #endregion

    }
}

SchoolManagement/SchoolManagement/Controllers/InformationPublicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SchoolManagement.Models;
using SchoolManagement.DAL;
using OfficeOpenXml;

namespace SchoolManagement.Controllers
{
    public class InformationPublicController : Controller
    {
        // GET: InformationPublic
        private InformationPublicDAL dal = new InformationPublicDAL();

        #region Users
        public ActionResult Teacher(string searchString, int? page, int pageSize = 10)
        {
            ViewBag.SearchString = searchString;
            return View(dal.getUser(searchString, 2, page, pageSize));
        }

        public ActionResult Student(string searchString, int? page, int pageSize = 10)
        {
            ViewBag.SearchString = searchString;
            return View(dal.getUser(searchString, 3, page, pageSize)); // 3-IDRole -Student
        }

        public ActionResult ListofClass(string searchString, int? page, int pageSize = 10)
        {
            ViewBag.searchString = searchString;
            return View(dal.getStudentClass(searchString, page, pageSize));
        }

        public ActionResult ViewListClass(string id, int? page, int pageSize = 10)
        {
            return View(dal.getViewStudentClass(id, page, pageSize));
        }

        #endregion

        #region All List
        public ActionResult ListSubject(string searchString, int? page, int pageSize = 10)
        {
            ViewBag.searchString = searchString;
            return View(dal.ListSubject(searchString, page, pageSize));
        }

        public ActionResult ListClass(string searchString, int? page, int pageSize = 10)
        {
            ViewBag.searchString = searchString;
            return View(dal.ListClass(searchString, page, pageSize));
        }

        public ActionResult ViewClass(string id, int? page, int pageSize = 20)
        {
            if (id == null)
                return RedirectToAction("ListClass");
            if (!page.HasValue)
                page = 1;
            return View(dal.ViewClass(id, page.Value, pageSize));
        }

        #endregion

        #region Div
        public ActionResult Project1(string searchString, int? page, int pageSize = 15)
        {
            ViewBag.searchString = searchString;
            return View(dal.DivProject("ET3170", searchString, page, pageSize));
        }

        public ActionResult Project2(string searchString, int? page, int pageSize = 15)
        {
            ViewBag.searchString = searchString;
            return View(dal.DivProject("ET4210", searchString, page, pageSize));
        }

        public ActionResult Project3(string searchString, int? page, int pageSize = 15)
        {
            ViewBag.searchString = searchString;
            return View(dal.DivProject("ET5020", searchString, page, pageSize));
        }

        public ActionResult DivClasses(string searchString, int? page, int pageSize = 15)
        {
            ViewBag.searchString = searchString;
            return View(dal.DivClass(searchString, page, pageSize));
        }
        #endregion

        #region Download file excel
        public void DownloadViewListClass(string idClass)
        {
            using (SchoolManagementEntities db = new SchoolManagementEntities())
            {
                List<Users> list = db.Users.Where(c => c.IDClass == idClass).OrderBy(c => c.Name).ToList();

                ExcelPackage package = new ExcelPackage();
                ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("List");

                worksheet.Cells["A1"].Value = "Course";
                worksheet.Cells["B1"].Value = list[0].Classes.Course;

                worksheet.Cells["A2"].Value = "Class";
                worksheet.Cells["B2"].Value = list[0].Classes.ClassName;

                worksheet.Cells["A3"].Value = "Date";
                worksheet.Cells["B3"].Value = string.Format("{0:dd MMMM yyyy} at {0:H: mm tt}", DateTimeOffset.Now);

                worksheet.Cells["A5"].Value = "STT";
                worksheet.Cells["B5"].Value = "MSSV";
                worksheet.Cells["C5"].Value = "Student";
                worksheet.Cells["D5"].Value = "Class";
                worksheet.Cells["E5"].Value = "Phone";
                worksheet.Cells["F5"].Value = "Email";
                worksheet.Cells["G5"].Value = "Address";

                int rowStart = 6;
                foreach (var item in list.ToList())
                {
                    worksheet.Cells[string.Format("A{0}", rowStart)].Value = rowStart - 5;
                    worksheet.Cells[string.Format("B{0}", rowStart)].Value = item.ID;
                    worksheet.Cells[string.Format("C{0}", rowStart)].Value = item.Name;
                    worksheet.Cells[string.Format("D{0}", rowStart)].Value = item.Classes.ClassName;
                    worksheet.Cells[string.Format("E{0}", rowStart)].Value = item.Phone;
                    worksheet.Cells[string.Format("F{0}", rowStart)].Value = item.Email;
                    worksheet.Cells[string.Format("G{0}", rowStart)].Value = item.Address;

                    rowStart++;
                }
                worksheet.Cells["A:AZ"].AutoFitColumns();

                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformat-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment: filename=" + "ExcelReport.xlsx");
                Response.BinaryWrite(package.GetAsByteArray());
                Response.End();
            }
        }

        public void DownloadViewClass(string idClass)
        {
            using (SchoolManagementEntities db = new SchoolManagementEntities())
            {
                List<RegistrationClasses> list = db.RegistrationClasses.Where(c => c.IDClass == idClass).OrderBy(c => c.Users.Name).ToList();

                ExcelPackage package = new ExcelPackage();
                ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("List");

                worksheet.Cells["A1"].Value = "Subject";
                worksheet.Cells["B1"].Value = list[0].Class_Subjects.Subjects.SubjectName;

                worksheet.Cells["A2"].Value = "IDSubject";
                worksheet.Cells["B2"].Value = list[0].Class_Subjects.SubjectID;

                worksheet.Cells["A3"].Value = "IDClass";
                worksheet.Cells["B3"].Value = list[0].IDClass;

                worksheet.Cells["A5"].Value = "STT";
                worksheet.Cells["B5"].Value = "MSSV";
                worksheet.Cells["C5"].Value = "Student";
                worksheet.Cells["D5"].Value = "Class";
                worksheet.Cells["E5"].Value = "Course";
                worksheet.Cells["F5"].Value = "Phone";
                worksheet.Cells["G5"].Value = "Email";
                worksheet.Cells["H5"].Value = "Address";

                int rowStart = 6;
                foreach (var item in list.ToList())
                {
                    worksheet.Cells[string.Format("A{0}", rowStart)].Value = rowStart - 5;
                    worksheet.Cells[string.Format("B{0}", rowStart)].Value = item.ID;
                    worksheet.Cells[string.Format("C{0}", rowStart)].Value = item.Users.Name;
                    worksheet.Cells[string.Format("D{0}", rowStart)].Value = item.Users.Classes.ClassName;
                    worksheet.Cells[string.Format("E{0}", rowStart)].Value = item.Users.Classes.Course;
                    worksheet.Cells[string.Format("F{0}", rowStart)].Value = item.Users.Phone;
                    worksheet.Cells[string.Format("G{0}", rowStart)].Value = item.Users.Email;
                    worksheet.Cells[string.Format("H{0}", rowStart)].Value = item.Users.Address;

                    rowStart++;
                }
                worksheet.Cells["A:AZ"].AutoFitColumns();

                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformat-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment: filename=" + "ExcelReport.xlsx");
                Response.BinaryWrite(package.GetAsByteArray());
                Response.End();
            }
        }

        public void DownloadProject(string idProject)

        {
            using (SchoolManagementEntities db = new SchoolManagementEntities())
            {
                List<DivionProjects> list = db.DivionProjects.Where(c => c.RegistrationClasses.Class_Subjects.SubjectID == idProject).OrderBy(c => c.Users.Name).ToList();

                ExcelPackage package = new ExcelPackage();
                ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("List");

                worksheet.Cells["A1"].Value = "Subject";
                worksheet.Cells["B1"].Value = list[0].RegistrationClasses.Class_Subjects.Subjects.SubjectName;

                worksheet.Cells["A2"].Value = "IDSubject";
                worksheet.Cells["B2"].Value = list[0].RegistrationClasses.Class_Subjects.SubjectID;

                worksheet.Cells["A3"].Value = "IDClass";
                worksheet.Cells["B3"].Value = list[0].RegistrationClasses.IDClass;

                worksheet.Cells["A5"].Value = "STT";
                worksheet.Cells["B5"].Value = "MSSV";
                worksheet.Cells["C5"].Value = "Student";
                worksheet.Cells["D5"].Value = "Class";
                worksheet.Cells["E5"].Value = "Teacher";
                worksheet.Cells["F5"].Value = "Bomon";
                worksheet.Cells["G5"].Value = "Phone";
                worksheet.Cells["H5"].Value = "Eamil";

                int rowStart = 6;
                foreach (var item in list.ToList())
                {
                    worksheet.Cells[string.Format("A{0}", rowStart)].Value = rowStart - 5;
                    worksheet.Cells[string.Format("B{0}", rowStart)].Value = item.RegistrationClasses.IDStudent;

SchoolManagement/SchoolManagement/Views/InformationPublic/DivClasses.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.DivisionClasses>
@using PagedList.Mvc;

@{
    ViewBag.Title = "DivClasses";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    int _stt = 1;
}
<section class="site-section">
    <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center">
            <br />
            <h2>DivClasses</h2>
        </div>
        <div class="col-md-7 text-center">
            @using (Html.BeginForm("DivClasses", "InformationPublic", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-12">
                        Select by Subject or Teacher
                        <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
                    </div>
                </div>
            }
            <br />
        </div>
        <div class="col-md-7 text-center">
            <table class=" table table-light" border="1" cellpadding="10" cellspacing="10">
                <tr>
                    <th>STT</th>
                    <th>IDClass</th>
                    <th>Subject</th>
                    <th>IDSubject</th>
                    <th>Time</th>
                    <th>ClassRoom</th>
                    <th>Teacher</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@_stt</td>
                        @{ _stt++;}
                        <td>@Html.DisplayFor(modelItem => item.IDClass)</td>
                        <td>@Html.DisplayFor(modelItem => item.Class_Subjects.Subjects.SubjectName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Class_Subjects.SubjectID)</td>
                        <td>@Html.DisplayFor(modelItem => item.Class_Subjects.Time)</td>
                        <td>@Html.DisplayFor(modelItem => item.Class_Subjects.Classroom)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Phone)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Email)</td>
                    </tr>
                }
            </table>
            <b>@Html.PagedListPager(Model, page => Url.Action("DivClasses", new { page, searchString = ViewBag.searchString }))</b>
        </div>
    </div>
</section>

SchoolManagement/SchoolManagement/Views/InformationPublic/ListClass.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.Class_Subjects>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ListClass";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<section class="site-section">
    <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center">
            <br />
            <h2>ListClass</h2>
        </div>
        <div class="col-md-7 text-center">
            @using (Html.BeginForm("ListClass", "InformationPublic", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-12">
                        Select Class
                        <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
                    </div>
                </div>
            }
            <br />
        </div>
        <div class="col-md-7 text-center">
            <table class=" table table-light" border="1" cellpadding="10" cellspacing="10">
                <tr>
                    <th>IDClass</th>
                    <th>IDSubject</th>
                    <th>SubjectName</th>
                    <th>Time</th>
                    <th>Classroom</th>
                    <th>ClassType</th>
                    <th>Note</th>
                    <th>ViewClass</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.ID)</td>
                        <td>@Html.DisplayFor(modelItem => item.SubjectID)</td>
                        <td>@Html.DisplayFor(modelItem => item.Subjects.SubjectName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Time)</td>
                        <td>@Html.DisplayFor(modelItem => item.Classroom)</td>
                        <td>@Html.DisplayFor(modelItem => item.ClassType)</td>
                        <td>@Html.DisplayFor(modelItem => item.Note)</td>
                        <td>@Html.ActionLink("View", "ViewClass", new { id = item.ID })</td>
                    </tr>
                }
            </table>
            <b>@Html.PagedListPager(Model, page => Url.Action("ListClass", new { page, searchString = ViewBag.searchString }))</b>
        </div>
    </div>
</section>

SchoolManagement/SchoolManagement/Views/InformationPublic/ListSubject.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.Subjects>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ListSubject";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<section class="site-section">
    <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center">
            <br />
            <h2>ListSubject</h2>
        </div>
        <div class="col-md-7 text-center">
            @using (Html.BeginForm("ListSubject", "InformationPublic", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-12">
                        Select Subject
                        <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
                    </div>
                </div>
            }
            <br />
        </div>
        <div class="col-md-7 text-center">
            <table class=" table table-light" border="1" cellpadding="10" cellspacing="10">
                <tr>
                    <th>ID</th>
                    <th>SubjectName</th>
                    <th>TC</th>
                    <th>TC_Fee</th>
                    <th>Note</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.ID)</td>
                        <td>@Html.DisplayFor(modelItem => item.SubjectName)</td>
                        <td>@Html.DisplayFor(modelItem => item.TC)</td>
                        <td>@Html.DisplayFor(modelItem => item.TC_Fee)</td>
                        <td>@Html.DisplayFor(modelItem => item.Note)</td>
                    </tr>
                }
            </table>
            <b>@Html.PagedListPager(Model, page => Url.Action("ListSubject", new { page, searchString = ViewBag.searchString }))</b>
        </div>
    </div>
</section>

SchoolManagement/SchoolManagement/Views/InformationPublic/ListofClass.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.Classes>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ListofClass";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    int _stt = 1;
}

<section class="site-section">
    <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center">
            <br />
            <h2>List of Class</h2>
        </div>
        <div class="col-md-7 text-center">
            <br />
            @using (Html.BeginForm("ListofClass", "InformationPublic", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-12">
                        Select Class
                        <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
                    </div>
                </div>
            }
            <br />
        </div>

        <div class="col-md-7 text-center">
            <table class=" table table-light" border="1" cellpadding="10" cellspacing="10">
                <tr>
                    <th>STT</th>
                    <th>ID</th>
                    <th>Class</th>
                    <th>Course</th>
                    <th>View Members</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@_stt</td>
                        @{ _stt++;}
                        <td>@Html.DisplayFor(modelItem => item.ID)</td>
                        <td>@Html.DisplayFor(modelItem => item.ClassName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Course)</td>
                        <td>@Html.ActionLink("View", "ViewListClass", new { id = item.ID })</td>
                    </tr>
                }

            </table>
            <b>@Html.PagedListPager(Model, page => Url.Action("ListofClass", new { page, searchString = ViewBag.searchString }))</b>
        </div>
    </div>
</section>

SchoolManagement/SchoolManagement/Views/InformationPublic/Project1.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.DivionProjects>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Project1";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    int _stt = 1;
}
<section class="site-section">
    <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center">
            <br />
            <h2>Project1</h2>
            <h6>You can @Html.ActionLink("download", "DownloadProject", new { idProject = "ET3170" }) file.</h6>
        </div>
        <div class="col-md-7 text-center">
            @using (Html.BeginForm("Project1", "InformationPublic", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-12">
                        Select by Student or Teacher
                        <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
                    </div>
                </div>
            }
            <br />
        </div>
        <div class="col-md-7 text-center">
            <table class=" table table-light" border="1" cellpadding="10" cellspacing="10">
                <tr>
                    <th>STT</th>
                    <th>MSSV</th>
                    <th>Student</th>
                    <th>Class</th>
                    <th>Teacher</th>
                    <th>Bộ môn</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@_stt</td>
                        @{ _stt++;}
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.ID)</td>
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.Classes.ClassName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Classes.ClassName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Phone)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Email)</td>
                    </tr>
                }

            </table>
            <b>@Html.PagedListPager(Model, page => Url.Action("Project1", new { page, searchString = ViewBag.searchString }))</b>
        </div>
    </div>
</section>

SchoolManagement/SchoolManagement/Views/InformationPublic/Project2.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.DivionProjects>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Project2";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    int _stt = 1;
}
<section class="site-section">
    <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center">
            <br />
            <h2>Project2</h2>
            <h6>You can @Html.ActionLink("download", "DownloadProject", new { idProject = "ET4210" }) file.</h6>
        </div>
        <div class="col-md-7 text-center">
            @using (Html.BeginForm("Project2", "InformationPublic", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-12">
                        Select by Student or Teacher
                        <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
                    </div>
                </div>
            }
            <br />
        </div>
        <div class="col-md-7 text-center">
            <table class=" table table-light" border="1" cellpadding="10" cellspacing="10">
                <tr>
                    <th>STT</th>
                    <th>MSSV</th>
                    <th>Student</th>
                    <th>Class</th>
                    <th>Teacher</th>
                    <th>Bộ môn</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@_stt</td>
                        @{ _stt++;}
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.ID)</td>
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.Classes.ClassName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Classes.ClassName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Phone)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Email)</td>
                    </tr>
                }

            </table>
            <b>@Html.PagedListPager(Model, page => Url.Action("Project2", new { page, searchString = ViewBag.searchString }))</b>
        </div>
    </div>
</section>

SchoolManagement/SchoolManagement/Views/InformationPublic/Project3.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.DivionProjects>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Project3";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    int _stt = 1;
}
<section class="site-section">
    <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center">
            <br />
            <h2>Project3</h2>
            <h6>You can @Html.ActionLink("download", "DownloadProject", new { idProject = "ET5020" }) file.</h6>
        </div>
        <div class="col-md-7 text-center">
            @using (Html.BeginForm("Project3", "InformationPublic", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-12">
                        Select by Student or Teacher
                        <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
                    </div>
                </div>
            }
            <br />
        </div>
        <div class="col-md-7 text-center">
            <table class=" table table-light" border="1" cellpadding="10" cellspacing="10">
                <tr>
                    <th>STT</th>
                    <th>MSSV</th>
                    <th>Student</th>
                    <th>Class</th>
                    <th>Teacher</th>
                    <th>Bộ môn</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@_stt</td>
                        @{ _stt++;}
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.ID)</td>
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.RegistrationClasses.Users.Classes.ClassName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Classes.ClassName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Phone)</td>
                        <td>@Html.DisplayFor(modelItem => item.Users.Email)</td>
                    </tr>
                }

            </table>
            <b>@Html.PagedListPager(Model, page => Url.Action("Project3", new { page, searchString = ViewBag.searchString }))</b>
        </div>
    </div>
</section>