SchoolManagement/SchoolManagement/Areas/Admin/Controllers/UserTeacherController.cs
using SchoolManagement.DAL;
using SchoolManagement.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SchoolManagement.Areas.Admin.Controllers
{
    public class UserTeacherController : Controller
    {
        // GET: Admin/UserTeacher
        private UsersDAL dal = new UsersDAL();

        public ActionResult Index(string searchString, int? page, int pageSize = 10)
        {
            try
            {
                ViewBag.searchString = searchString;
                int idRole = 2;
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 1)
                    return View(dal.getSearchUsers(idRole, searchString, page, pageSize));
                else
                    return View("Error", "Admin");
            }
            catch { return View("Error", "Admin"); }
        }

        public ActionResult Edit(string id)
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 1)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    Users user = dal.getByID(id);
                    if (user == null)
                        return HttpNotFound();
                    return View(user);
                }
                else
                    return View("Error");
            }
            catch { return View("Error", "Admin"); }
        }

        [HttpPost]
        public ActionResult Edit(Users user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    dal.Update(user);
                    return RedirectToAction("Index");
                }
                return View(user);
            }
            catch
            {
                user.LoginErrorMessage = "Error! Check input(Password, IDClass, IDRole)";
                return View(user);
            }
        }

        public ActionResult Delete(string id)
        {
            try
            {
                if (CheckDAL.CheckRole((int)Session["IDRole"]) == 1)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Users user = dal.getByID(id);
                    if (user == null)
                    {
                        return HttpNotFound();
                    }
                    return View(user);
                }
                else
                    return View("Error");
            }
            catch { return View("Error", "Admin"); }
        }

        [HttpPost]
        public ActionResult Delete(string id, Users user)
        {
            if (id != null)
            {
                using (SchoolManagementEntities db = new SchoolManagementEntities())
                {
                    db.DivionProjects.RemoveRange(db.DivionProjects.Where(u => u.IDTeacher == id));
                    db.DivisionClasses.RemoveRange(db.DivisionClasses.Where(u => u.IDTeacher == id));
                }
                dal.Delete(id);
            }
            return RedirectToAction("Index");
        }
    }
}

SchoolManagement/SchoolManagement/Areas/Admin/Views/UserTeacher/Delete.cshtml
@model SchoolManagement.Models.Users

@{
    ViewBag.Title = "Admin Page";
    Layout = "~/Views/SharedTemplate/_LayoutAdmin.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Delete Teacher</h1>
    </div>
</div>
<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Admin")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Teacher", "Index", "UserTeacher")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Delete", "Delete", "UserTeacher")</li>
</ol>

<h4>Are you sure you want to delete this?</h4>
<div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Classes.ClassName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Roles.RoleName)
            </th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.ID)
            </td>
            <td>
                @Html.DisplayFor(model => model.Password)
            </td>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.Classes.ClassName)
            </td>
            <td>
                @Html.DisplayFor(model => model.Email)
            </td>
            <td>
                @Html.DisplayFor(model => model.Phone)
            </td>
            <td>
                @Html.DisplayFor(model => model.Address)
            </td>
            <td>
                @Html.DisplayFor(model => model.Roles.RoleName)
            </td>
        </tr>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolManagement/SchoolManagement/Areas/Admin/Views/UserTeacher/Edit.cshtml
@model SchoolManagement.Models.Users

@{
    ViewBag.Title = "Admin Page";
    Layout = "~/Views/SharedTemplate/_LayoutAdmin.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Teacher</h1>
    </div>
</div>
<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Admin")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Teacher", "Index", "UserTeacher")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Edit", "Edit", "UserTeacher")</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="color: red"><label class="field-validation-error">@Html.DisplayFor(model => model.LoginErrorMessage)</label></h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.IDClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDClass, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.IDClass, "Class", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IDClass", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDClass, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDRole, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.IDRole, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDRole, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.IDRole, "Role", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IDRole", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDRole, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

SchoolManagement/SchoolManagement/Areas/Admin/Views/UserTeacher/Index.cshtml
@model PagedList.IPagedList<SchoolManagement.Models.Users>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Admin Page";
    Layout = "~/Views/SharedTemplate/_LayoutAdmin.cshtml";
    int _stt = 1;
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Teacher</h1>
    </div>
</div>
<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Admin")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Teacher", "Index", "UserTeacher")</li>
</ol>
<p>This is page All Teachers</p>

@using (Html.BeginForm("Index", "UserTeacher", FormMethod.Get))
{
    <div class="row">
        <div class="col-lg-12">
            Select by ID, Class, Name or Address
            <input type="text" name="searchString" value="@ViewBag.searchString" /> <button type="submit">Search</button>
        </div>
    </div>
}
<br />

<table class="table table-bordered" id="dataTable">
    <tr>
        <th>STT</th>
        <th>ID</th>
        @*<th>Password</th>*@
        <th>Name</th>
        <th>Bo Mon</th>
        <th>Email </th>
        <th>Phone</th>
        <th>Address</th>
        <th>Role</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@_stt</td>
            @{ _stt++;}
            <td>@Html.DisplayFor(modelItem => item.ID)</td>
            @*<td>@Html.DisplayFor(modelItem => item.Password)</td>*@
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Classes.ClassName)</td>
            <td>@Html.DisplayFor(modelItem => item.Email)</td>
            <td>@Html.DisplayFor(modelItem => item.Phone)</td>
            <td>@Html.DisplayFor(modelItem => item.Address)</td>
            <td>@Html.DisplayFor(modelItem => item.Roles.RoleName)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) or
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>
<b>@Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchString = ViewBag.searchString }))</b>